### ISSUE TITLE
Request for docs?

### ISSUE THREAD

**Issue by ChrisDoufu** [ashblue/pathfinding-platformer#1]
Hi, I am interested in this project. It's like that you have built a complete system to abstractly model a platformer and apply A* to pathfinding. I happen to be working on a project that focuses on a similar topic recently. 

The issue is that I find it hard to understand the logic behind your [demo](http://ashblue.github.io/pathfinding-platformer/). I also couldn't figure out the meaning of some words, such as Opened Set and Closed Set in Tile Legend. 

Do you have any documentation that explains the basic logic behind the project? It would help a lot if you could share it. Thanks :)

**Comment by ashblue** [comment]
Hey @ChrisDoufu I gave a speech on A* basics some years back. Here is a video of it. Should get you what you need I think.

https://youtu.be/7kMbPU_6Me4
